version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=bytesupply.com
      - LETSENCRYPT_HOST=bytesupply.com
      - BS_SERVICE_VERSION=PRODUCTION
      - BS_LOGFILE=/go/bin/log/bytesupply.log
      - BS_MSGFILE=/go/bin/log/message.log
      - BS_STATIC_LOCATION=/go/bin/static/
      - BS_TEMPLATE_LOCATION=/go/bin/templates/
      - BS_SERVER_PORT=:80
      #- BS_GOOGLE_SEARCH_API_KEY=AIzaSyDKwOVyqeicqLps8Rnvazyyub5AoT16c1o
      - BS_MYSQL_USERNAME=bytesupply
      - BS_MYSQL_PASSWORD=a6bd3f10339b2d39aaa6175484a38173c1061f4a
      - BS_MYSQL_HOST=db-mysql-nyc1-bytesupply-do-user-5896777-0.b.db.ondigitalocean.com
      - BS_MYSQL_PORT=25060
      - BS_MYSQL_DB=bytesupply
      #sslmode = REQUIRED
