version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=localhost
      - LETSENCRYPT_HOST=bytesupply.com
      - BS_SERVICE_VERSION=PRODUCTION
      - BS_LOGFILE=/go/bin/log/bytesupply.log
      - BS_MSGFILE=/go/bin/log/message.log
      - BS_STATIC_LOCATION=/go/bin/static/
      - BS_SERVER_PORT=:80
      - BS_MYSQL_USERNAME=doadmin
      - BS_MYSQL_PASSWORD=f1cny78efclvx2jy
      - BS_MYSQL_HOST=db-mysql-nyc1-bytesupply-do-user-5896777-0.b.db.ondigitalocean.com
      - BS_MYSQL_PORT=25060
      - BS_MYSQL_DB=defaultdb
      #sslmode = REQUIRED
